title: Gaurav Sehgal
email: gauravsehgal93@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Writing my thoughts one blog at a time.
base_url: "/"
url: "http://gauravsehgal.github.io"
twitter_username: gaurav__sehgal
github_username:  gauravsehgal

markdown: kramdown
